import type { Locale } from "../../types/app";
import type { TherapistQuestion, TherapistQuestionOption } from "../../types/therapist";

const therapistTitleOptions: Record<Locale, TherapistQuestionOption[]> = {
  en: [
    { id: "psychotherapist", label: "Psychotherapist" },
    { id: "psychologist", label: "Psychologist" },
    { id: "psychiatrist", label: "Psychiatrist" },
    { id: "clinical_psychologist", label: "Clinical psychologist" },
    { id: "family_therapist", label: "Family therapist" },
    { id: "couples_therapist", label: "Couples therapist" },
    { id: "sex_therapist", label: "Sex therapist" },
    { id: "brief_therapist", label: "Brief therapist" },
    { id: "trauma_therapist", label: "Trauma therapist" },
    { id: "integrative_psychotherapist", label: "Integrative psychotherapist" },
    { id: "cognitive_psychotherapist", label: "Cognitive psychotherapist" },
    { id: "psychodynamic_psychotherapist", label: "Psychodynamic psychotherapist" },
    { id: "solution_focused_therapist", label: "Solution-focused therapist" },
    { id: "mental_health_nurse", label: "Mental health nurse" },
    { id: "social_worker", label: "Social worker" },
    { id: "other", label: "Other" },
  ],
  fi: [
    { id: "psychotherapist", label: "Psykoterapeutti" },
    { id: "psychologist", label: "Psykologi" },
    { id: "psychiatrist", label: "Psykiatri" },
    { id: "clinical_psychologist", label: "Kliininen psykologi" },
    { id: "family_therapist", label: "Perheterapeutti" },
    { id: "couples_therapist", label: "Pariterapeutti" },
    { id: "sex_therapist", label: "Seksuaaliterapeutti" },
    { id: "brief_therapist", label: "Lyhytterapeutti" },
    { id: "trauma_therapist", label: "Traumaterapeutti" },
    { id: "integrative_psychotherapist", label: "Integratiivinen psykoterapeutti" },
    { id: "cognitive_psychotherapist", label: "Kognitiivinen psykoterapeutti" },
    { id: "psychodynamic_psychotherapist", label: "Psykodynaaminen psykoterapeutti" },
    { id: "solution_focused_therapist", label: "Ratkaisukeskeinen terapeutti" },
    { id: "mental_health_nurse", label: "Psykiatrinen sairaanhoitaja" },
    { id: "social_worker", label: "Sosiaalityöntekijä" },
    { id: "other", label: "Muu" },
  ],
};

const therapistQuizByLocale: Record<Locale, TherapistQuestion[]> = {
  en: [
    {
      id: "identity",
      category: "Profile basics",
      prompt: "Name, title, and email*",
      type: "group",
      required: true,
      fields: [
        {
          id: "name",
          label: "Name",
          required: true,
          description: "First name and last name",
        },
        {
          id: "title",
          label: "Title",
          type: "select",
          required: true,
          description: "Choose the professional title clients should see, for example psychotherapist or psychologist",
          options: therapistTitleOptions.en,
        },
        {
          id: "title_custom",
          label: "Other title",
          required: true,
          description: "Add your title if it is not listed above",
          showWhen: {
            fieldId: "title",
            values: ["Other"],
          },
        },
        { id: "email", label: "Email", type: "email", required: true },
      ],
    },
    {
      id: "gender_identity",
      category: "Identity",
      prompt: "Gender identity",
      type: "single",
      required: true,
      options: [
        { id: "woman", label: "Woman" },
        { id: "man", label: "Man" },
        { id: "non_binary", label: "Non-binary" },
        { id: "prefer_not_to_say", label: "Prefer not to say" },
      ],
    },
    {
      id: "education",
      category: "Background",
      prompt: "Education and graduation year*",
      description: "We verify your professional background and build client trust from the very first meeting",
      type: "text",
      required: true,
    },
    {
      id: "years_experience",
      category: "Background",
      prompt: "How many years have you done therapeutic client work?*",
      description: "This helps us match clients based on their preference for lived experience",
      type: "number",
      required: true,
      min: 0,
      max: 40,
      step: 1,
      minLabel: "0 years",
      maxLabel: "40 years",
    },
    {
      id: "negative_therapy_experience",
      category: "Client fit",
      prompt: "Do you have experience with clients who have had a previous negative experience with therapy?",
      description: "Helps us direct clients who need special support to more experienced professionals",
      type: "text",
      required: false,
    },
    {
      id: "kela_provider",
      category: "Practicalities",
      prompt: "Are you a Kela-approved rehabilitation psychotherapy service provider?*",
      description: "Critical information for managing client expectations and financial planning",
      type: "single",
      required: true,
      options: [
        { id: "yes", label: "Yes" },
        { id: "no", label: "No" },
      ],
    },
    {
      id: "language_skills",
      category: "Practicalities",
      prompt: "Language skills",
      description: "Essential basic information so we can ensure smooth communication and matching",
      type: "multi",
      required: true,
      options: [
        { id: "finnish", label: "Finnish" },
        { id: "swedish", label: "Swedish" },
        { id: "english", label: "English" },
      ],
    },
    {
      id: "price_per_session",
      category: "Practicalities",
      prompt: "Price per session (45–60 min)*",
      description: "Helps clients find a professional within their budget and reduces financial uncertainty",
      type: "number",
      required: true,
    },
    {
      id: "appointment_frequency",
      category: "Practicalities",
      prompt: "What appointment frequencies do you typically offer?*",
      description: "Logistical confirmation that your schedule and the client's needs (e.g. weekly support) align",
      type: "single",
      required: true,
      options: [
        { id: "intensive", label: "Intensive (once a week)" },
        { id: "flexible", label: "Flexible (a few times a month)" },
        { id: "infrequent", label: "Infrequent (once a month / as needed)" },
      ],
    },
    {
      id: "session_format",
      category: "Practicalities",
      prompt: "Session format*",
      type: "single",
      required: true,
      options: [
        { id: "remote_only", label: "Remote only" },
        { id: "in_person_only", label: "In-person only" },
        { id: "both", label: "Both remote and in-person" },
      ],
    },
    {
      id: "specializations",
      category: "Clinical fit",
      prompt: "Your strongest areas of specialization*",
      description: "Research shows that matching based on the client's primary concern (e.g. burnout) improves treatment outcomes",
      type: "multi",
      required: true,
      maxSelections: 5,
      options: [
        { id: "stress_burnout", label: "Stress and burnout" },
        { id: "relationships_family", label: "Relationships and family" },
        { id: "depression_low_mood", label: "Depression and low mood" },
        { id: "anxiety_fears", label: "Anxiety and fears" },
        { id: "crises_grief", label: "Crises and grief" },
        { id: "self_esteem_identity", label: "Self-esteem and identity" },
        { id: "parenthood", label: "Parenthood" },
        { id: "neurodiversity", label: "Neurodiversity (ADHD etc.)" },
        { id: "academic_pressure", label: "Academic and performance pressure" },
      ],
    },
    {
      id: "work_focus",
      category: "Clinical fit",
      prompt: "What does your work typically focus on?*",
      description: "We ensure your method (e.g. solution-focused) matches the client's wishes (e.g. concrete tools)",
      type: "single",
      required: true,
      options: [
        { id: "self_understanding", label: "Deepening self-understanding and insights" },
        { id: "concrete_problems", label: "Solving concrete problems" },
        { id: "holistic_change", label: "Holistic life change" },
      ],
    },
    {
      id: "working_style",
      category: "Working style",
      prompt: "My working style is…*",
      description: "How you meet clients in terms of style is the most researched key factor in building a strong therapeutic relationship",
      type: "scale",
      required: true,
      minLabel: "1 = Listening and permissive",
      maxLabel: "5 = Goal-oriented and directive",
    },
    {
      id: "pace_of_progress",
      category: "Working style",
      prompt: "Pace of progress*",
      description: "Helps us find a client who shares your preferred working rhythm, whether that's brisk and goal-focused or calm and reflective",
      type: "scale",
      required: true,
      minLabel: "1 = Calm and unhurried",
      maxLabel: "5 = Goal-oriented and swift",
    },
    {
      id: "interaction_style",
      category: "Working style",
      prompt: "Interaction style*",
      description: "Style compatibility is one of the most researched factors in building a trusting and effective working alliance",
      type: "scale",
      required: true,
      minLabel: "1 = Relaxed and informal",
      maxLabel: "5 = Clear and professional",
    },
    {
      id: "meet_client_style",
      category: "Working style",
      prompt: "Which of the following best describes how you meet a client?*",
      description: "Human chemistry is individual. This helps the client recognize in whose company they feel safest",
      type: "single",
      required: true,
      options: [
        { id: "calm_gentle", label: "Calm and gentle" },
        { id: "honest_direct", label: "Honest and direct" },
        { id: "warm_encouraging", label: "Warm and encouraging" },
        { id: "analytical_structured", label: "Analytical and structured" },
      ],
    },
    {
      id: "office_location",
      category: "Practicalities",
      prompt: "Office location (if in-person)",
      type: "group",
      required: false,
      fields: [
        {
          id: "street_address",
          label: "Street address",
          description: "Street name and number",
        },
        {
          id: "postal_code",
          label: "Postal code",
        },
        {
          id: "city",
          label: "City",
        },
        {
          id: "country",
          label: "Country",
        },
      ],
    },
    {
      id: "client_intro",
      category: "Public profile",
      prompt: "Write a short, freeform introduction of yourself for clients",
      description: "This is your 'voice' to the client. Describe for example how you typically meet people, or what is important to you in your work. This text will be shown to clients alongside match results",
      type: "text",
      required: true,
      note: "Write as little or as much as you want. This will become the heart of your public introduction.",
    },
    {
      id: "profile_photo_url",
      category: "Public profile",
      prompt: "Profile photo (optional)",
      description: "Add a clear headshot if you have one. Clients often decide whether a profile feels trustworthy before they read the full text.",
      type: "image-upload",
      required: false,
    },
    {
      id: "contact_preference",
      category: "Practicalities",
      prompt: "How do you want clients to find you?",
      description: "Add a website, an email address, or both. Clients will see this in your recommendation card and contact panel.",
      type: "group",
      required: true,
      groupRequirement: {
        mode: "atLeastOne",
        fieldIds: ["website", "contact_email"],
      },
      fields: [
        {
          id: "website",
          label: "Website",
          type: "url",
          description: "Your website or booking page",
        },
        {
          id: "contact_email",
          label: "Email",
          type: "email",
          description: "An email address clients can use to reach you",
        },
      ],
    },
    {
      id: "privacy_consent",
      category: "Consent",
      prompt: "Privacy and consent*",
      description: "I accept that Myötä processes the information I provide for the purpose of offering the matching service. The information is confidential and will be used to create your profile. You can request deletion of your data at any time.",
      type: "single",
      required: true,
      options: [
        { id: "accept", label: "I accept" },
        { id: "decline", label: "I don't accept" },
      ],
    },
  ],
  fi: [
    {
      id: "identity",
      category: "Profiilin perusteet",
      prompt: "Nimi, titteli ja sähköposti*",
      type: "group",
      required: true,
      fields: [
        {
          id: "name",
          label: "Nimi",
          required: true,
          description: "Etu- ja sukunimi",
        },
        {
          id: "title",
          label: "Titteli",
          type: "select",
          required: true,
          description: "Valitse ammattinimike, joka näkyy asiakkaille, esimerkiksi psykoterapeutti tai psykologi",
          options: therapistTitleOptions.fi,
        },
        {
          id: "title_custom",
          label: "Muu titteli",
          required: true,
          description: "Lisää titteli, jos sitä ei löydy listalta",
          showWhen: {
            fieldId: "title",
            values: ["Muu"],
          },
        },
        { id: "email", label: "Sähköposti", type: "email", required: true },
      ],
    },
    {
      id: "gender_identity",
      category: "Identiteetti",
      prompt: "Sukupuoli-identiteetti",
      type: "single",
      required: true,
      options: [
        { id: "woman", label: "Nainen" },
        { id: "man", label: "Mies" },
        { id: "non_binary", label: "Muunsukupuolinen" },
        { id: "prefer_not_to_say", label: "En halua määritellä" },
      ],
    },
    {
      id: "education",
      category: "Tausta",
      prompt: "Koulutus ja valmistumisvuosi*",
      description: "Varmistamme ammatillisen taustasi ja rakennamme asiakkaan luottamusta jo ensimmäisestä kohtaamisesta lähtien",
      type: "text",
      required: true,
    },
    {
      id: "years_experience",
      category: "Tausta",
      prompt: "Kuinka monta vuotta olet tehnyt terapeuttista asiakastyötä?*",
      description: "Tämä auttaa meitä matchaamaan asiakkaita myös heidän kokemustoiveensa perusteella",
      type: "number",
      required: true,
      min: 0,
      max: 40,
      step: 1,
      minLabel: "0 vuotta",
      maxLabel: "40 vuotta",
    },
    {
      id: "negative_therapy_experience",
      category: "Asiakassopivuus",
      prompt: "Onko sinulla kokemusta asiakkaista, joilla on ollut aiemmin negatiivinen terapiakokemus?",
      description: "Auttaa meitä ohjaamaan erityistä tukea tarvitsevat asiakkaat kokeneemmille ammattilaisille",
      type: "text",
      required: false,
    },
    {
      id: "kela_provider",
      category: "Käytännöt",
      prompt: "Oletko Kelan hyväksymä kuntoutuspsykoterapian palveluntuottaja?*",
      description: "Kriittinen tieto asiakkaan odotusten ja taloudellisen suunnittelun kannalta",
      type: "single",
      required: true,
      options: [
        { id: "yes", label: "Kyllä" },
        { id: "no", label: "Ei" },
      ],
    },
    {
      id: "language_skills",
      category: "Käytännöt",
      prompt: "Kielitaito",
      description: "Perustieto, jolla varmistamme sujuvan kommunikaation ja matchin",
      type: "multi",
      required: true,
      options: [
        { id: "finnish", label: "Suomi" },
        { id: "swedish", label: "Ruotsi" },
        { id: "english", label: "Englanti" },
      ],
    },
    {
      id: "price_per_session",
      category: "Käytännöt",
      prompt: "Hinta per käynti (45–60 min)*",
      description: "Auttaa asiakasta löytämään ammattilaisen budjettinsa sisältä ja vähentää taloudellista epävarmuutta",
      type: "number",
      required: true,
    },
    {
      id: "appointment_frequency",
      category: "Käytännöt",
      prompt: "Millaisia tapaamistiheyksiä yleensä tarjoat?*",
      description: "Logistinen varmistus siitä, että aikataulusi ja asiakkaan tarve (esim. viikoittainen tuki) sopivat yhteen",
      type: "single",
      required: true,
      options: [
        { id: "intensive", label: "Tiivis (kerran viikossa)" },
        { id: "flexible", label: "Joustava (pari kertaa kuussa)" },
        { id: "infrequent", label: "Harva (kerran kuussa / tarvittaessa)" },
      ],
    },
    {
      id: "session_format",
      category: "Käytännöt",
      prompt: "Tapaamismuoto*",
      type: "single",
      required: true,
      options: [
        { id: "remote_only", label: "Vain etäyhteys" },
        { id: "in_person_only", label: "Vain kasvotusten" },
        { id: "both", label: "Sekä että" },
      ],
    },
    {
      id: "specializations",
      category: "Kliininen sopivuus",
      prompt: "Vahvimmat erityisosaamisalueesi*",
      description: "Tutkimusten mukaan match asiakkaan ensisijaisen huolen (esim. uupumus) perusteella parantaa hoidon tuloksia",
      type: "multi",
      required: true,
      maxSelections: 5,
      options: [
        { id: "stress_burnout", label: "Stressi ja uupumus" },
        { id: "relationships_family", label: "Ihmissuhteet ja perhe" },
        { id: "depression_low_mood", label: "Masennus ja alakulo" },
        { id: "anxiety_fears", label: "Ahdistuneisuus ja pelot" },
        { id: "crises_grief", label: "Kriisit ja suru" },
        { id: "self_esteem_identity", label: "Itsetunto ja identiteetti" },
        { id: "parenthood", label: "Vanhemmuus" },
        { id: "neurodiversity", label: "Neurokirjo (ADHD jne)" },
        { id: "academic_pressure", label: "Opiskelu ja suoriutuspaineet" },
      ],
    },
    {
      id: "work_focus",
      category: "Kliininen sopivuus",
      prompt: "Mihin työsi tyypillisesti keskittyy?*",
      description: "Varmistamme, että menetelmäsi (esim. ratkaisukeskeinen) vastaa asiakkaan toiveisiin (esim. konkreettiset työkalut)",
      type: "single",
      required: true,
      options: [
        { id: "self_understanding", label: "Itseymmärryksen ja oivallusten syventämiseen" },
        { id: "concrete_problems", label: "Konkreettisten ongelmien ratkaisemiseen" },
        { id: "holistic_change", label: "Kokonaisvaltaiseen elämänmuutokseen" },
      ],
    },
    {
      id: "working_style",
      category: "Työskentelytyyli",
      prompt: "Työskentelytyylini on…*",
      description: "Se, miten kohtaat asiakkaan tyylillisesti, on yksi tutkituimmista tekijöistä vahvan terapiasuhteen rakentumisessa",
      type: "scale",
      required: true,
      minLabel: "1 = Kuunteleva ja salliva",
      maxLabel: "5 = Tavoitteellinen ja ohjaava",
    },
    {
      id: "pace_of_progress",
      category: "Työskentelytyyli",
      prompt: "Etenemisen tahti*",
      description: "Auttaa löytämään asiakkaan, joka jakaa toivomasi työskentelyrytmin, oli se sitten ripeä ja tavoitteellinen tai rauhallinen ja reflektoiva",
      type: "scale",
      required: true,
      minLabel: "1 = Rauhallinen ja kiireetön",
      maxLabel: "5 = Tavoitteellinen ja ripeä",
    },
    {
      id: "interaction_style",
      category: "Työskentelytyyli",
      prompt: "Vuorovaikutustyyli*",
      description: "Tyylien yhteensopivuus on yksi tutkituimmista tekijöistä luottamuksellisen ja toimivan työskentelysuhteen rakentumisessa",
      type: "scale",
      required: true,
      minLabel: "1 = Rento ja vapaamuotoinen",
      maxLabel: "5 = Selkeä ja ammatillinen",
    },
    {
      id: "meet_client_style",
      category: "Työskentelytyyli",
      prompt: "Mikä seuraavista kuvaa parhaiten sitä, miten kohtaat asiakkaan?*",
      description: "Ihmiskemia on yksilöllistä. Tämä auttaa asiakasta tunnistamaan, kenen seurassa hän kokee olonsa turvallisimmaksi",
      type: "single",
      required: true,
      options: [
        { id: "calm_gentle", label: "Rauhallinen ja lempeä" },
        { id: "honest_direct", label: "Rehellinen ja suora" },
        { id: "warm_encouraging", label: "Lämmin ja rohkaiseva" },
        { id: "analytical_structured", label: "Analyyttinen ja jäsennelty" },
      ],
    },
    {
      id: "office_location",
      category: "Käytännöt",
      prompt: "Vastaanoton osoite (jos tarjoat lähitapaamisia)",
      type: "group",
      required: false,
      fields: [
        {
          id: "street_address",
          label: "Katuosoite",
          description: "Kadun nimi ja numero",
        },
        {
          id: "postal_code",
          label: "Postinumero",
        },
        {
          id: "city",
          label: "Kaupunki",
        },
        {
          id: "country",
          label: "Maa",
        },
      ],
    },
    {
      id: "client_intro",
      category: "Julkinen profiili",
      prompt: "Kirjoita lyhyt vapaa esittelytekstisi asiakkaille",
      description: "Tämä on sinun 'äänesi' asiakkaalle. Kuvaa esimerkiksi, miten yleensä kohtaat ihmisiä tai mikä työssäsi on sinulle tärkeää. Tämä teksti näytetään asiakkaille match-tulosten yhteydessä",
      type: "text",
      required: true,
      note: "Kirjoita niin vähän tai paljon kuin haluat. Tästä muodostuu julkisen esittelysi ydin.",
    },
    {
      id: "profile_photo_url",
      category: "Julkinen profiili",
      prompt: "Profiilikuva (valinnainen)",
      description: "Lisää selkeä kasvokuva, jos sinulla on sellainen. Asiakas muodostaa usein ensivaikutelman jo ennen koko tekstin lukemista.",
      type: "image-upload",
      required: false,
    },
    {
      id: "contact_preference",
      category: "Käytännöt",
      prompt: "Miten haluat asiakkaiden löytävän sinut?",
      description: "Lisää verkkosivu, sähköpostiosoite tai molemmat. Asiakkaat näkevät nämä suosituskortissa ja yhteystietopaneelissa.",
      type: "group",
      required: true,
      groupRequirement: {
        mode: "atLeastOne",
        fieldIds: ["website", "contact_email"],
      },
      fields: [
        {
          id: "website",
          label: "Verkkosivu",
          type: "url",
          description: "Verkkosivusi tai varauslinkkisi",
        },
        {
          id: "contact_email",
          label: "Sähköposti",
          type: "email",
          description: "Sähköpostiosoite, josta asiakkaat tavoittavat sinut",
        },
      ],
    },
    {
      id: "privacy_consent",
      category: "Suostumus",
      prompt: "Tietosuoja ja suostumus*",
      description: "Hyväksyn, että Myötä käsittelee antamiani tietoja match-palvelun tarjoamiseksi. Tiedot ovat luottamuksellisia ja niitä käytetään profiilisi luomiseen. Voit pyytää tietojesi poistamista milloin tahansa.",
      type: "single",
      required: true,
      options: [
        { id: "accept", label: "Hyväksyn" },
        { id: "decline", label: "En hyväksy" },
      ],
    },
  ],
};

export function getTherapistQuiz(locale: Locale) {
  return therapistQuizByLocale[locale];
}
